auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

# Les configurations du stockage et du schéma doivent être à la racine
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

# La section common doit seulement contenir les paramètres qui lui sont propres
common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
