server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  # Loki est accessible via son nom de service Docker, qui est 'loki'
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-app-logs
          environment: dev
          application: smart-spring
          __path__: /logs/application.log
    pipeline_stages:
      - regex:
          # Capture l'horodatage, le thread, le niveau de log et le nom du logger
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) \[(?P<thread>[^\]]+)\] (?P<level>[A-Z]+) (?P<logger>[^ ]+) - (?P<message>.*)$'
      - labels:
          # CORRECTION: Doit être une liste de chaînes sous la clé 'labels'
          labels:
            - level
            - thread
